#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBayPopularItemTrend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="searchresults")]
	public partial class eBayPopularItemTrendDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserteBayCategory(eBayCategory instance);
    partial void UpdateeBayCategory(eBayCategory instance);
    partial void DeleteeBayCategory(eBayCategory instance);
    partial void InserteBayCountrySiteId(eBayCountrySiteId instance);
    partial void UpdateeBayCountrySiteId(eBayCountrySiteId instance);
    partial void DeleteeBayCountrySiteId(eBayCountrySiteId instance);
    partial void InserteBayPopularItemTrend(eBayPopularItemTrend instance);
    partial void UpdateeBayPopularItemTrend(eBayPopularItemTrend instance);
    partial void DeleteeBayPopularItemTrend(eBayPopularItemTrend instance);
    partial void InserteBaySubCategory(eBaySubCategory instance);
    partial void UpdateeBaySubCategory(eBaySubCategory instance);
    partial void DeleteeBaySubCategory(eBaySubCategory instance);
    partial void InserteBayTrendMasterSetting(eBayTrendMasterSetting instance);
    partial void UpdateeBayTrendMasterSetting(eBayTrendMasterSetting instance);
    partial void DeleteeBayTrendMasterSetting(eBayTrendMasterSetting instance);
    #endregion
		
		public eBayPopularItemTrendDBDataContext() : 
				base(global::eBayPopularItemTrend.Properties.Settings.Default.searchresultsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public eBayPopularItemTrendDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eBayPopularItemTrendDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eBayPopularItemTrendDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eBayPopularItemTrendDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<eBayCategory> eBayCategories
		{
			get
			{
				return this.GetTable<eBayCategory>();
			}
		}
		
		public System.Data.Linq.Table<eBayCountrySiteId> eBayCountrySiteIds
		{
			get
			{
				return this.GetTable<eBayCountrySiteId>();
			}
		}
		
		public System.Data.Linq.Table<eBayPopularItemTrend> eBayPopularItemTrends
		{
			get
			{
				return this.GetTable<eBayPopularItemTrend>();
			}
		}
		
		public System.Data.Linq.Table<eBaySubCategory> eBaySubCategories
		{
			get
			{
				return this.GetTable<eBaySubCategory>();
			}
		}
		
		public System.Data.Linq.Table<eBayTrendMasterSetting> eBayTrendMasterSettings
		{
			get
			{
				return this.GetTable<eBayTrendMasterSetting>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_eBayPopularItemTrend")]
		public int SP_eBayPopularItemTrend(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExecutionDate", DbType="Date")] System.Nullable<System.DateTime> executionDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnderCategory", DbType="VarChar(250)")] string underCategory, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemID", DbType="VarChar(20)")] string itemID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTime", DbType="DateTime")] System.Nullable<System.DateTime> endTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ViewItemURLForNaturalSearch", DbType="VarChar(250)")] string viewItemURLForNaturalSearch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListingType", DbType="VarChar(50)")] string listingType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GalleryURL", DbType="VarChar(150)")] string galleryURL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimaryCategoryID", DbType="VarChar(30)")] string primaryCategoryID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimaryCategoryName", DbType="VarChar(250)")] string primaryCategoryName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BidCount", DbType="Int")] System.Nullable<int> bidCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConvertedCurrentPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> convertedCurrentPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListingStatus", DbType="VarChar(15)")] string listingStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string currencyID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(250)")] string title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingServiceCost", DbType="Decimal(10,2)")] System.Nullable<decimal> shippingServiceCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShippingType", DbType="VarChar(10)")] string shippingType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ListedShippingServiceCost", DbType="Decimal(10,2)")] System.Nullable<decimal> listedShippingServiceCost, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="WatchCount", DbType="Int")] System.Nullable<int> watchCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), executionDate, underCategory, itemID, endTime, viewItemURLForNaturalSearch, listingType, galleryURL, primaryCategoryID, primaryCategoryName, bidCount, convertedCurrentPrice, listingStatus, currencyID, title, shippingServiceCost, shippingType, listedShippingServiceCost, watchCount, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(18)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_eBaySetting")]
		public int SP_eBaySetting([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="Int")] System.Nullable<int> action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NextExecutionDate", DbType="DateTime")] System.Nullable<System.DateTime> nextExecutionDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDateTime", DbType="DateTime")] System.Nullable<System.DateTime> startDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompleteDateTime", DbType="DateTime")] System.Nullable<System.DateTime> completeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(10)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="Int")] ref System.Nullable<int> output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action, nextExecutionDate, startDateTime, completeDateTime, status, output);
			output = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eBayCategorySchedule")]
		public int eBayCategorySchedule([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] ref string executionDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, executionDate);
			executionDate = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eBayPopularItemCallSchedular")]
		public int eBayPopularItemCallSchedular([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] ref string executionDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, executionDate);
			executionDate = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eBaySubCategorySchedule")]
		public int eBaySubCategorySchedule([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] ref string executionDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, executionDate);
			executionDate = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBayCategory")]
	public partial class eBayCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CategoryId;
		
		private string _CategoryName;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private string _eBaySiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCategoryIdChanging(string value);
    partial void OnCategoryIdChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedOnChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    #endregion
		
		public eBayCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(25)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(100)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBayCountrySiteId")]
	public partial class eBayCountrySiteId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _eBaySiteId;
		
		private string _SiteName;
		
		private string _GlobalID;
		
		private char _Active;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnGlobalIDChanging(string value);
    partial void OnGlobalIDChanged();
    partial void OnActiveChanging(char value);
    partial void OnActiveChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    #endregion
		
		public eBayCountrySiteId()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(250)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalID", DbType="VarChar(100)")]
		public string GlobalID
		{
			get
			{
				return this._GlobalID;
			}
			set
			{
				if ((this._GlobalID != value))
				{
					this.OnGlobalIDChanging(value);
					this.SendPropertyChanging();
					this._GlobalID = value;
					this.SendPropertyChanged("GlobalID");
					this.OnGlobalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Char(1) NOT NULL")]
		public char Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBayPopularItemTrend")]
	public partial class eBayPopularItemTrend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _ExecutionDate;
		
		private string _UnderCategory;
		
		private string _UnderCategoryId;
		
		private string _ItemID;
		
		private System.DateTime _EndTime;
		
		private string _ViewItemURLForNaturalSearch;
		
		private string _ListingType;
		
		private string _GalleryURL;
		
		private string _PrimaryCategoryID;
		
		private string _PrimaryCategoryName;
		
		private System.Nullable<int> _BidCount;
		
		private System.Nullable<decimal> _ConvertedCurrentPrice;
		
		private string _ListingStatus;
		
		private string _currencyID;
		
		private string _Title;
		
		private System.Nullable<decimal> _ShippingServiceCost;
		
		private string _ShippingType;
		
		private System.Nullable<decimal> _ListedShippingServiceCost;
		
		private System.Nullable<int> _WatchCount;
		
		private string _eBaySiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnExecutionDateChanging(System.DateTime value);
    partial void OnExecutionDateChanged();
    partial void OnUnderCategoryChanging(string value);
    partial void OnUnderCategoryChanged();
    partial void OnUnderCategoryIdChanging(string value);
    partial void OnUnderCategoryIdChanged();
    partial void OnItemIDChanging(string value);
    partial void OnItemIDChanged();
    partial void OnEndTimeChanging(System.DateTime value);
    partial void OnEndTimeChanged();
    partial void OnViewItemURLForNaturalSearchChanging(string value);
    partial void OnViewItemURLForNaturalSearchChanged();
    partial void OnListingTypeChanging(string value);
    partial void OnListingTypeChanged();
    partial void OnGalleryURLChanging(string value);
    partial void OnGalleryURLChanged();
    partial void OnPrimaryCategoryIDChanging(string value);
    partial void OnPrimaryCategoryIDChanged();
    partial void OnPrimaryCategoryNameChanging(string value);
    partial void OnPrimaryCategoryNameChanged();
    partial void OnBidCountChanging(System.Nullable<int> value);
    partial void OnBidCountChanged();
    partial void OnConvertedCurrentPriceChanging(System.Nullable<decimal> value);
    partial void OnConvertedCurrentPriceChanged();
    partial void OnListingStatusChanging(string value);
    partial void OnListingStatusChanged();
    partial void OncurrencyIDChanging(string value);
    partial void OncurrencyIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnShippingServiceCostChanging(System.Nullable<decimal> value);
    partial void OnShippingServiceCostChanged();
    partial void OnShippingTypeChanging(string value);
    partial void OnShippingTypeChanged();
    partial void OnListedShippingServiceCostChanging(System.Nullable<decimal> value);
    partial void OnListedShippingServiceCostChanged();
    partial void OnWatchCountChanging(System.Nullable<int> value);
    partial void OnWatchCountChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    #endregion
		
		public eBayPopularItemTrend()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutionDate", DbType="Date NOT NULL")]
		public System.DateTime ExecutionDate
		{
			get
			{
				return this._ExecutionDate;
			}
			set
			{
				if ((this._ExecutionDate != value))
				{
					this.OnExecutionDateChanging(value);
					this.SendPropertyChanging();
					this._ExecutionDate = value;
					this.SendPropertyChanged("ExecutionDate");
					this.OnExecutionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnderCategory", DbType="VarChar(MAX)")]
		public string UnderCategory
		{
			get
			{
				return this._UnderCategory;
			}
			set
			{
				if ((this._UnderCategory != value))
				{
					this.OnUnderCategoryChanging(value);
					this.SendPropertyChanging();
					this._UnderCategory = value;
					this.SendPropertyChanged("UnderCategory");
					this.OnUnderCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnderCategoryId", DbType="VarChar(MAX)")]
		public string UnderCategoryId
		{
			get
			{
				return this._UnderCategoryId;
			}
			set
			{
				if ((this._UnderCategoryId != value))
				{
					this.OnUnderCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._UnderCategoryId = value;
					this.SendPropertyChanged("UnderCategoryId");
					this.OnUnderCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="VarChar(MAX)")]
		public string ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this.OnItemIDChanging(value);
					this.SendPropertyChanging();
					this._ItemID = value;
					this.SendPropertyChanged("ItemID");
					this.OnItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime NOT NULL")]
		public System.DateTime EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemURLForNaturalSearch", DbType="VarChar(MAX)")]
		public string ViewItemURLForNaturalSearch
		{
			get
			{
				return this._ViewItemURLForNaturalSearch;
			}
			set
			{
				if ((this._ViewItemURLForNaturalSearch != value))
				{
					this.OnViewItemURLForNaturalSearchChanging(value);
					this.SendPropertyChanging();
					this._ViewItemURLForNaturalSearch = value;
					this.SendPropertyChanged("ViewItemURLForNaturalSearch");
					this.OnViewItemURLForNaturalSearchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListingType", DbType="VarChar(MAX)")]
		public string ListingType
		{
			get
			{
				return this._ListingType;
			}
			set
			{
				if ((this._ListingType != value))
				{
					this.OnListingTypeChanging(value);
					this.SendPropertyChanging();
					this._ListingType = value;
					this.SendPropertyChanged("ListingType");
					this.OnListingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryURL", DbType="VarChar(MAX)")]
		public string GalleryURL
		{
			get
			{
				return this._GalleryURL;
			}
			set
			{
				if ((this._GalleryURL != value))
				{
					this.OnGalleryURLChanging(value);
					this.SendPropertyChanging();
					this._GalleryURL = value;
					this.SendPropertyChanged("GalleryURL");
					this.OnGalleryURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCategoryID", DbType="VarChar(MAX)")]
		public string PrimaryCategoryID
		{
			get
			{
				return this._PrimaryCategoryID;
			}
			set
			{
				if ((this._PrimaryCategoryID != value))
				{
					this.OnPrimaryCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCategoryID = value;
					this.SendPropertyChanged("PrimaryCategoryID");
					this.OnPrimaryCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCategoryName", DbType="VarChar(MAX)")]
		public string PrimaryCategoryName
		{
			get
			{
				return this._PrimaryCategoryName;
			}
			set
			{
				if ((this._PrimaryCategoryName != value))
				{
					this.OnPrimaryCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._PrimaryCategoryName = value;
					this.SendPropertyChanged("PrimaryCategoryName");
					this.OnPrimaryCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidCount", DbType="Int")]
		public System.Nullable<int> BidCount
		{
			get
			{
				return this._BidCount;
			}
			set
			{
				if ((this._BidCount != value))
				{
					this.OnBidCountChanging(value);
					this.SendPropertyChanging();
					this._BidCount = value;
					this.SendPropertyChanged("BidCount");
					this.OnBidCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvertedCurrentPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ConvertedCurrentPrice
		{
			get
			{
				return this._ConvertedCurrentPrice;
			}
			set
			{
				if ((this._ConvertedCurrentPrice != value))
				{
					this.OnConvertedCurrentPriceChanging(value);
					this.SendPropertyChanging();
					this._ConvertedCurrentPrice = value;
					this.SendPropertyChanged("ConvertedCurrentPrice");
					this.OnConvertedCurrentPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListingStatus", DbType="VarChar(MAX)")]
		public string ListingStatus
		{
			get
			{
				return this._ListingStatus;
			}
			set
			{
				if ((this._ListingStatus != value))
				{
					this.OnListingStatusChanging(value);
					this.SendPropertyChanging();
					this._ListingStatus = value;
					this.SendPropertyChanged("ListingStatus");
					this.OnListingStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyID", DbType="VarChar(MAX)")]
		public string currencyID
		{
			get
			{
				return this._currencyID;
			}
			set
			{
				if ((this._currencyID != value))
				{
					this.OncurrencyIDChanging(value);
					this.SendPropertyChanging();
					this._currencyID = value;
					this.SendPropertyChanged("currencyID");
					this.OncurrencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingServiceCost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ShippingServiceCost
		{
			get
			{
				return this._ShippingServiceCost;
			}
			set
			{
				if ((this._ShippingServiceCost != value))
				{
					this.OnShippingServiceCostChanging(value);
					this.SendPropertyChanging();
					this._ShippingServiceCost = value;
					this.SendPropertyChanged("ShippingServiceCost");
					this.OnShippingServiceCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingType", DbType="VarChar(MAX)")]
		public string ShippingType
		{
			get
			{
				return this._ShippingType;
			}
			set
			{
				if ((this._ShippingType != value))
				{
					this.OnShippingTypeChanging(value);
					this.SendPropertyChanging();
					this._ShippingType = value;
					this.SendPropertyChanged("ShippingType");
					this.OnShippingTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListedShippingServiceCost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ListedShippingServiceCost
		{
			get
			{
				return this._ListedShippingServiceCost;
			}
			set
			{
				if ((this._ListedShippingServiceCost != value))
				{
					this.OnListedShippingServiceCostChanging(value);
					this.SendPropertyChanging();
					this._ListedShippingServiceCost = value;
					this.SendPropertyChanged("ListedShippingServiceCost");
					this.OnListedShippingServiceCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WatchCount", DbType="Int")]
		public System.Nullable<int> WatchCount
		{
			get
			{
				return this._WatchCount;
			}
			set
			{
				if ((this._WatchCount != value))
				{
					this.OnWatchCountChanging(value);
					this.SendPropertyChanging();
					this._WatchCount = value;
					this.SendPropertyChanged("WatchCount");
					this.OnWatchCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBaySubCategory")]
	public partial class eBaySubCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CategoryId;
		
		private string _SubCategoryId;
		
		private string _SubCategoryName;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private string _eBaySiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCategoryIdChanging(string value);
    partial void OnCategoryIdChanged();
    partial void OnSubCategoryIdChanging(string value);
    partial void OnSubCategoryIdChanged();
    partial void OnSubCategoryNameChanging(string value);
    partial void OnSubCategoryNameChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedOnChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    #endregion
		
		public eBaySubCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(25)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryId", DbType="VarChar(25)")]
		public string SubCategoryId
		{
			get
			{
				return this._SubCategoryId;
			}
			set
			{
				if ((this._SubCategoryId != value))
				{
					this.OnSubCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._SubCategoryId = value;
					this.SendPropertyChanged("SubCategoryId");
					this.OnSubCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryName", DbType="VarChar(100)")]
		public string SubCategoryName
		{
			get
			{
				return this._SubCategoryName;
			}
			set
			{
				if ((this._SubCategoryName != value))
				{
					this.OnSubCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._SubCategoryName = value;
					this.SendPropertyChanged("SubCategoryName");
					this.OnSubCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBayTrendMasterSetting")]
	public partial class eBayTrendMasterSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _NextExecutionDate;
		
		private System.Nullable<System.DateTime> _StartDateTime;
		
		private System.Nullable<System.DateTime> _CompleteDateTime;
		
		private string _Status;
		
		private string _Type;
		
		private string _eBaySiteId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNextExecutionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnNextExecutionDateChanged();
    partial void OnStartDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateTimeChanged();
    partial void OnCompleteDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCompleteDateTimeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    #endregion
		
		public eBayTrendMasterSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextExecutionDate", DbType="Date")]
		public System.Nullable<System.DateTime> NextExecutionDate
		{
			get
			{
				return this._NextExecutionDate;
			}
			set
			{
				if ((this._NextExecutionDate != value))
				{
					this.OnNextExecutionDateChanging(value);
					this.SendPropertyChanging();
					this._NextExecutionDate = value;
					this.SendPropertyChanged("NextExecutionDate");
					this.OnNextExecutionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDateTime
		{
			get
			{
				return this._StartDateTime;
			}
			set
			{
				if ((this._StartDateTime != value))
				{
					this.OnStartDateTimeChanging(value);
					this.SendPropertyChanging();
					this._StartDateTime = value;
					this.SendPropertyChanged("StartDateTime");
					this.OnStartDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompleteDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CompleteDateTime
		{
			get
			{
				return this._CompleteDateTime;
			}
			set
			{
				if ((this._CompleteDateTime != value))
				{
					this.OnCompleteDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CompleteDateTime = value;
					this.SendPropertyChanged("CompleteDateTime");
					this.OnCompleteDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(5)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
