#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="searchresults")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbamazon(tbamazon instance);
    partial void Updatetbamazon(tbamazon instance);
    partial void Deletetbamazon(tbamazon instance);
    partial void Inserttbebay(tbebay instance);
    partial void Updatetbebay(tbebay instance);
    partial void Deletetbebay(tbebay instance);
    partial void Inserttbgoogle(tbgoogle instance);
    partial void Updatetbgoogle(tbgoogle instance);
    partial void Deletetbgoogle(tbgoogle instance);
    partial void Inserttbimage(tbimage instance);
    partial void Updatetbimage(tbimage instance);
    partial void Deletetbimage(tbimage instance);
    partial void Inserttbsearch(tbsearch instance);
    partial void Updatetbsearch(tbsearch instance);
    partial void Deletetbsearch(tbsearch instance);
    partial void InserteBayCountrySiteId(eBayCountrySiteId instance);
    partial void UpdateeBayCountrySiteId(eBayCountrySiteId instance);
    partial void DeleteeBayCountrySiteId(eBayCountrySiteId instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["searchresultsConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbamazon> tbamazons
		{
			get
			{
				return this.GetTable<tbamazon>();
			}
		}
		
		public System.Data.Linq.Table<tbebay> tbebays
		{
			get
			{
				return this.GetTable<tbebay>();
			}
		}
		
		public System.Data.Linq.Table<tbgoogle> tbgoogles
		{
			get
			{
				return this.GetTable<tbgoogle>();
			}
		}
		
		public System.Data.Linq.Table<tbimage> tbimages
		{
			get
			{
				return this.GetTable<tbimage>();
			}
		}
		
		public System.Data.Linq.Table<tbsearch> tbsearches
		{
			get
			{
				return this.GetTable<tbsearch>();
			}
		}
		
		public System.Data.Linq.Table<eBayCountrySiteId> eBayCountrySiteIds
		{
			get
			{
				return this.GetTable<eBayCountrySiteId>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertsearch")]
		public int insertsearch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string keyword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.saveimage")]
		public int saveimage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string small, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string medium, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string large, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> keywordid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), small, medium, large, keywordid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CategoriesInTrend")]
		public ISingleResult<SP_CategoriesInTrendResult> SP_CategoriesInTrend()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_CategoriesInTrendResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CategoriesInTrend_V2")]
		public ISingleResult<SP_CategoriesInTrend_V2Result> SP_CategoriesInTrend_V2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_CategoriesInTrend_V2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_TopSubCategoryInTrend_V2")]
		public ISingleResult<SP_TopSubCategoryInTrend_V2Result> SP_TopSubCategoryInTrend_V2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="VarChar(100)")] string categoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryId, startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_TopSubCategoryInTrend_V2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ItemInTrend_V2")]
		public ISingleResult<SP_ItemInTrend_V2Result> SP_ItemInTrend_V2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="VarChar(100)")] string categoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryId, startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_ItemInTrend_V2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CategoriesInTrend_V2")]
		public ISingleResult<SP_CategoriesInTrend_V2Result1> SP_CategoriesInTrend_V21([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_CategoriesInTrend_V2Result1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CategoriesInTrend_V3")]
		public ISingleResult<SP_CategoriesInTrend_V3Result> SP_CategoriesInTrend_V3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_CategoriesInTrend_V3Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ItemInTrend_V3")]
		public ISingleResult<SP_ItemInTrend_V3Result> SP_ItemInTrend_V3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="VarChar(100)")] string categoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, categoryId, startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_ItemInTrend_V3Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_TopSubCategoryInTrend_V3")]
		public ISingleResult<SP_TopSubCategoryInTrend_V3Result> SP_TopSubCategoryInTrend_V3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string eBaySiteId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="VarChar(100)")] string categoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> startPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndPrice", DbType="Decimal(10,2)")] System.Nullable<decimal> endPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eBaySiteId, categoryId, startDate, endDate, startPrice, endPrice);
			return ((ISingleResult<SP_TopSubCategoryInTrend_V3Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_eBayItemDetail")]
		public ISingleResult<SP_eBayItemDetailResult> SP_eBayItemDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="VarChar(20)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string eBaySiteId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, eBaySiteId);
			return ((ISingleResult<SP_eBayItemDetailResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbamazon")]
	public partial class tbamazon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _keywordid;
		
		private string _title;
		
		private string _price;
		
		private System.Nullable<int> _imageid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkeywordidChanging(System.Nullable<int> value);
    partial void OnkeywordidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void OnimageidChanging(System.Nullable<int> value);
    partial void OnimageidChanged();
    #endregion
		
		public tbamazon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywordid", DbType="Int")]
		public System.Nullable<int> keywordid
		{
			get
			{
				return this._keywordid;
			}
			set
			{
				if ((this._keywordid != value))
				{
					this.OnkeywordidChanging(value);
					this.SendPropertyChanging();
					this._keywordid = value;
					this.SendPropertyChanged("keywordid");
					this.OnkeywordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(250)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(50)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageid", DbType="Int")]
		public System.Nullable<int> imageid
		{
			get
			{
				return this._imageid;
			}
			set
			{
				if ((this._imageid != value))
				{
					this.OnimageidChanging(value);
					this.SendPropertyChanging();
					this._imageid = value;
					this.SendPropertyChanged("imageid");
					this.OnimageidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbebay")]
	public partial class tbebay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _kewordid;
		
		private string _title;
		
		private System.Nullable<double> _price;
		
		private string _priceUnit;
		
		private System.Nullable<int> _imageid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkewordidChanging(System.Nullable<int> value);
    partial void OnkewordidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnpriceUnitChanging(string value);
    partial void OnpriceUnitChanged();
    partial void OnimageidChanging(System.Nullable<int> value);
    partial void OnimageidChanged();
    #endregion
		
		public tbebay()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kewordid", DbType="Int")]
		public System.Nullable<int> kewordid
		{
			get
			{
				return this._kewordid;
			}
			set
			{
				if ((this._kewordid != value))
				{
					this.OnkewordidChanging(value);
					this.SendPropertyChanging();
					this._kewordid = value;
					this.SendPropertyChanged("kewordid");
					this.OnkewordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(250)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceUnit", DbType="VarChar(50)")]
		public string priceUnit
		{
			get
			{
				return this._priceUnit;
			}
			set
			{
				if ((this._priceUnit != value))
				{
					this.OnpriceUnitChanging(value);
					this.SendPropertyChanging();
					this._priceUnit = value;
					this.SendPropertyChanged("priceUnit");
					this.OnpriceUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageid", DbType="Int")]
		public System.Nullable<int> imageid
		{
			get
			{
				return this._imageid;
			}
			set
			{
				if ((this._imageid != value))
				{
					this.OnimageidChanging(value);
					this.SendPropertyChanging();
					this._imageid = value;
					this.SendPropertyChanged("imageid");
					this.OnimageidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbgoogle")]
	public partial class tbgoogle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _keywordid;
		
		private string _title;
		
		private System.Nullable<double> _price;
		
		private string _priceunit;
		
		private string _marchantname;
		
		private System.Nullable<int> _imageid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkeywordidChanging(int value);
    partial void OnkeywordidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnpriceunitChanging(string value);
    partial void OnpriceunitChanged();
    partial void OnmarchantnameChanging(string value);
    partial void OnmarchantnameChanged();
    partial void OnimageidChanging(System.Nullable<int> value);
    partial void OnimageidChanged();
    #endregion
		
		public tbgoogle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywordid", DbType="Int NOT NULL")]
		public int keywordid
		{
			get
			{
				return this._keywordid;
			}
			set
			{
				if ((this._keywordid != value))
				{
					this.OnkeywordidChanging(value);
					this.SendPropertyChanging();
					this._keywordid = value;
					this.SendPropertyChanged("keywordid");
					this.OnkeywordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceunit", DbType="NVarChar(50)")]
		public string priceunit
		{
			get
			{
				return this._priceunit;
			}
			set
			{
				if ((this._priceunit != value))
				{
					this.OnpriceunitChanging(value);
					this.SendPropertyChanging();
					this._priceunit = value;
					this.SendPropertyChanged("priceunit");
					this.OnpriceunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marchantname", DbType="NVarChar(100)")]
		public string marchantname
		{
			get
			{
				return this._marchantname;
			}
			set
			{
				if ((this._marchantname != value))
				{
					this.OnmarchantnameChanging(value);
					this.SendPropertyChanging();
					this._marchantname = value;
					this.SendPropertyChanged("marchantname");
					this.OnmarchantnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageid", DbType="Int")]
		public System.Nullable<int> imageid
		{
			get
			{
				return this._imageid;
			}
			set
			{
				if ((this._imageid != value))
				{
					this.OnimageidChanging(value);
					this.SendPropertyChanging();
					this._imageid = value;
					this.SendPropertyChanged("imageid");
					this.OnimageidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbimage")]
	public partial class tbimage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _imageid;
		
		private string _imageurlsmall;
		
		private string _imageurlmedium;
		
		private string _imageurllarge;
		
		private System.Nullable<int> _imagekeywordid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnimageidChanging(int value);
    partial void OnimageidChanged();
    partial void OnimageurlsmallChanging(string value);
    partial void OnimageurlsmallChanged();
    partial void OnimageurlmediumChanging(string value);
    partial void OnimageurlmediumChanged();
    partial void OnimageurllargeChanging(string value);
    partial void OnimageurllargeChanged();
    partial void OnimagekeywordidChanging(System.Nullable<int> value);
    partial void OnimagekeywordidChanged();
    #endregion
		
		public tbimage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int imageid
		{
			get
			{
				return this._imageid;
			}
			set
			{
				if ((this._imageid != value))
				{
					this.OnimageidChanging(value);
					this.SendPropertyChanging();
					this._imageid = value;
					this.SendPropertyChanged("imageid");
					this.OnimageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurlsmall", DbType="NVarChar(MAX)")]
		public string imageurlsmall
		{
			get
			{
				return this._imageurlsmall;
			}
			set
			{
				if ((this._imageurlsmall != value))
				{
					this.OnimageurlsmallChanging(value);
					this.SendPropertyChanging();
					this._imageurlsmall = value;
					this.SendPropertyChanged("imageurlsmall");
					this.OnimageurlsmallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurlmedium", DbType="NVarChar(MAX)")]
		public string imageurlmedium
		{
			get
			{
				return this._imageurlmedium;
			}
			set
			{
				if ((this._imageurlmedium != value))
				{
					this.OnimageurlmediumChanging(value);
					this.SendPropertyChanging();
					this._imageurlmedium = value;
					this.SendPropertyChanged("imageurlmedium");
					this.OnimageurlmediumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageurllarge", DbType="NVarChar(MAX)")]
		public string imageurllarge
		{
			get
			{
				return this._imageurllarge;
			}
			set
			{
				if ((this._imageurllarge != value))
				{
					this.OnimageurllargeChanging(value);
					this.SendPropertyChanging();
					this._imageurllarge = value;
					this.SendPropertyChanged("imageurllarge");
					this.OnimageurllargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagekeywordid", DbType="Int")]
		public System.Nullable<int> imagekeywordid
		{
			get
			{
				return this._imagekeywordid;
			}
			set
			{
				if ((this._imagekeywordid != value))
				{
					this.OnimagekeywordidChanging(value);
					this.SendPropertyChanging();
					this._imagekeywordid = value;
					this.SendPropertyChanged("imagekeywordid");
					this.OnimagekeywordidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbsearch")]
	public partial class tbsearch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _keywordid;
		
		private string _searchkeyword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkeywordidChanging(int value);
    partial void OnkeywordidChanged();
    partial void OnsearchkeywordChanging(string value);
    partial void OnsearchkeywordChanged();
    #endregion
		
		public tbsearch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywordid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int keywordid
		{
			get
			{
				return this._keywordid;
			}
			set
			{
				if ((this._keywordid != value))
				{
					this.OnkeywordidChanging(value);
					this.SendPropertyChanging();
					this._keywordid = value;
					this.SendPropertyChanged("keywordid");
					this.OnkeywordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchkeyword", DbType="NVarChar(250)")]
		public string searchkeyword
		{
			get
			{
				return this._searchkeyword;
			}
			set
			{
				if ((this._searchkeyword != value))
				{
					this.OnsearchkeywordChanging(value);
					this.SendPropertyChanging();
					this._searchkeyword = value;
					this.SendPropertyChanged("searchkeyword");
					this.OnsearchkeywordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eBayCountrySiteId")]
	public partial class eBayCountrySiteId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _eBaySiteId;
		
		private string _SiteName;
		
		private string _GlobalID;
		
		private char _Active;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OneBaySiteIdChanging(string value);
    partial void OneBaySiteIdChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnGlobalIDChanging(string value);
    partial void OnGlobalIDChanged();
    partial void OnActiveChanging(char value);
    partial void OnActiveChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    #endregion
		
		public eBayCountrySiteId()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eBaySiteId", DbType="VarChar(5)")]
		public string eBaySiteId
		{
			get
			{
				return this._eBaySiteId;
			}
			set
			{
				if ((this._eBaySiteId != value))
				{
					this.OneBaySiteIdChanging(value);
					this.SendPropertyChanging();
					this._eBaySiteId = value;
					this.SendPropertyChanged("eBaySiteId");
					this.OneBaySiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(250)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalID", DbType="VarChar(100)")]
		public string GlobalID
		{
			get
			{
				return this._GlobalID;
			}
			set
			{
				if ((this._GlobalID != value))
				{
					this.OnGlobalIDChanging(value);
					this.SendPropertyChanging();
					this._GlobalID = value;
					this.SendPropertyChanged("GlobalID");
					this.OnGlobalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Char(1) NOT NULL")]
		public char Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_CategoriesInTrendResult
	{
		
		private string _CategoryId;
		
		private string _Category;
		
		private System.Nullable<int> _Watch;
		
		public SP_CategoriesInTrendResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(MAX)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(MAX)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_CategoriesInTrend_V2Result
	{
		
		private string _CategoryId;
		
		private System.DateTime _ExecutionDate;
		
		private string _Category;
		
		private System.Nullable<int> _Watch;
		
		public SP_CategoriesInTrend_V2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(MAX)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecutionDate", DbType="Date NOT NULL")]
		public System.DateTime ExecutionDate
		{
			get
			{
				return this._ExecutionDate;
			}
			set
			{
				if ((this._ExecutionDate != value))
				{
					this._ExecutionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(MAX)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_TopSubCategoryInTrend_V2Result
	{
		
		private string _SubCategoryId;
		
		private string _SubCategoryName;
		
		private System.Nullable<int> _Watch;
		
		public SP_TopSubCategoryInTrend_V2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryId", DbType="VarChar(25)")]
		public string SubCategoryId
		{
			get
			{
				return this._SubCategoryId;
			}
			set
			{
				if ((this._SubCategoryId != value))
				{
					this._SubCategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryName", DbType="VarChar(100)")]
		public string SubCategoryName
		{
			get
			{
				return this._SubCategoryName;
			}
			set
			{
				if ((this._SubCategoryName != value))
				{
					this._SubCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_ItemInTrend_V2Result
	{
		
		private string _Item;
		
		private string _ViewItemURLForNaturalSearch;
		
		private string _Title;
		
		private System.Nullable<int> _Watch;
		
		private string _Ids;
		
		public SP_ItemInTrend_V2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="VarChar(MAX)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemURLForNaturalSearch", DbType="VarChar(MAX)")]
		public string ViewItemURLForNaturalSearch
		{
			get
			{
				return this._ViewItemURLForNaturalSearch;
			}
			set
			{
				if ((this._ViewItemURLForNaturalSearch != value))
				{
					this._ViewItemURLForNaturalSearch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ids", DbType="VarChar(MAX)")]
		public string Ids
		{
			get
			{
				return this._Ids;
			}
			set
			{
				if ((this._Ids != value))
				{
					this._Ids = value;
				}
			}
		}
	}
	
	public partial class SP_CategoriesInTrend_V2Result1
	{
		
		private string _CategoryId;
		
		private string _Category;
		
		private System.Nullable<int> _Watch;
		
		public SP_CategoriesInTrend_V2Result1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(25)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_CategoriesInTrend_V3Result
	{
		
		private string _CategoryId;
		
		private string _Category;
		
		private System.Nullable<int> _Watch;
		
		public SP_CategoriesInTrend_V3Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="VarChar(25)")]
		public string CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_ItemInTrend_V3Result
	{
		
		private string _Item;
		
		private string _ViewItemURLForNaturalSearch;
		
		private string _Title;
		
		private System.Nullable<int> _Watch;
		
		private string _Ids;
		
		public SP_ItemInTrend_V3Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="VarChar(MAX)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemURLForNaturalSearch", DbType="VarChar(MAX)")]
		public string ViewItemURLForNaturalSearch
		{
			get
			{
				return this._ViewItemURLForNaturalSearch;
			}
			set
			{
				if ((this._ViewItemURLForNaturalSearch != value))
				{
					this._ViewItemURLForNaturalSearch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ids", DbType="VarChar(MAX)")]
		public string Ids
		{
			get
			{
				return this._Ids;
			}
			set
			{
				if ((this._Ids != value))
				{
					this._Ids = value;
				}
			}
		}
	}
	
	public partial class SP_TopSubCategoryInTrend_V3Result
	{
		
		private string _SubCategoryId;
		
		private string _SubCategoryName;
		
		private System.Nullable<int> _Watch;
		
		public SP_TopSubCategoryInTrend_V3Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryId", DbType="VarChar(25)")]
		public string SubCategoryId
		{
			get
			{
				return this._SubCategoryId;
			}
			set
			{
				if ((this._SubCategoryId != value))
				{
					this._SubCategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryName", DbType="VarChar(100)")]
		public string SubCategoryName
		{
			get
			{
				return this._SubCategoryName;
			}
			set
			{
				if ((this._SubCategoryName != value))
				{
					this._SubCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watch", DbType="Int")]
		public System.Nullable<int> Watch
		{
			get
			{
				return this._Watch;
			}
			set
			{
				if ((this._Watch != value))
				{
					this._Watch = value;
				}
			}
		}
	}
	
	public partial class SP_eBayItemDetailResult
	{
		
		private string _ViewItemURLForNaturalSearch;
		
		private string _GalleryURL;
		
		private string _Title;
		
		private System.Nullable<decimal> _price;
		
		private string _Category;
		
		public SP_eBayItemDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemURLForNaturalSearch", DbType="VarChar(MAX)")]
		public string ViewItemURLForNaturalSearch
		{
			get
			{
				return this._ViewItemURLForNaturalSearch;
			}
			set
			{
				if ((this._ViewItemURLForNaturalSearch != value))
				{
					this._ViewItemURLForNaturalSearch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryURL", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GalleryURL
		{
			get
			{
				return this._GalleryURL;
			}
			set
			{
				if ((this._GalleryURL != value))
				{
					this._GalleryURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(MAX)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
